name: mm_store_inventory
description: A Flutter app for managing store inventory with barcode scanning.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  mobile_scanner: ^3.5.6

flutter:
  uses-material-design: true
